[tool.poetry]
name = "2023_ithelp_marathron"
version = "0.1.0"
description = ""
authors = ["nick <nick1998chen0725@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
